import type { Metadata } from "next";
import { Poppins, Geist } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ChartColumnBigIcon } from "lucide-react";
import { ClerkProvider, Show, SignInButton, SignUpButton, UserButton } from '@clerk/nextjs'
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import UserDropdown from "./user-dropdown";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <ClerkProvider>
      <html lang="en" className={cn("font-sans", geist.variable)}>
        <body className={`${poppins.variable} antialiased`}>
          <nav className="bg-primary p-4 text-white h-20 flex items-center justify-between">
            <Link
              href="/"
              className="font-bold text-2xl flex gap-1 items-center"
            >
              <ChartColumnBigIcon className="text-lime-500" /> NextCash
            </Link>
            <div>
            <Show when="signed-out">
                <div className="flex items-center">
                  <SignInButton asChild>
                    <Button variant="link" className="text-white">
                      Sign in
                    </Button>
                  </SignInButton>

                  <SignUpButton asChild>
                    <Button variant="link" className="text-white">
                      Sign up
                    </Button>
                  </SignUpButton>
                </div>
            </Show>
            <Show when="signed-in">
              <UserDropdown />
            </Show>
            </div>
          </nav>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
